---
title: "ABC-XYZ-Analyse"
author: "Alexander Opris, Felix Mayer, Lukas Felzmann"
output:
  html_notebook:
    toc: true
    toc_float: true
    code_folding: none
    number_sections: true
---

```{r include=FALSE}
library(DBI)
library(odbc)
library(dplyr)
library(tidyr)
library(stringr)
library(glue)
library(ggplot2)
library(rlang)
readRenviron("../env_files/.Renviron.postgres")


```

```{r include=FALSE}
con <- DBI::dbConnect(odbc::odbc(),
                      Driver   = "PostgreSQL Unicode(x64)",
                      Server   = Sys.getenv("host"),
                      Database = Sys.getenv("dbname"),
                      UID      = Sys.getenv("user"),
                      PWD      = Sys.getenv("password"),
                      Port     = Sys.getenv("port"))
```

```{r include=FALSE}
get_table_as_tibble <- function(connection, table_name){
  query <- glue("select * from {table_name}")
  tmp <- dbGetQuery(conn=connection, statement = query)
  return(as_tibble(tmp))
}
```

```{r include=FALSE}
verkaeufe <- get_table_as_tibble(con, "verkaeufe")
```

# ABC-Analyse

## Nach Zugriffen
Ein Zugriff bedeutet, dass wegen einem Artikel ins Lager gegangen werden muss. Hierbei ist es unerheblich, wie viele Verpackungseinheiten aus dem Lager geholt werden.

```{r}
abc_analyse_nach_zugriffen <- verkaeufe %>%
  group_by(materialnummer) %>%
  summarise(anzahl_zugriffe = n()) %>%
  arrange(desc(anzahl_zugriffe)) %>% 
  mutate(rang = row_number()) %>% 
  mutate(anteil = anzahl_zugriffe/sum(anzahl_zugriffe)) %>% 
  mutate(anteil_kumuliert = cumsum(anteil)) %>% 
  mutate(klasse=
           case_when(
             anteil_kumuliert <= 0.8 ~ "A",
             anteil_kumuliert > 0.8 & anteil_kumuliert <= 0.9 ~ "B",
             TRUE ~ "C"
             )
         ) %>% 
  mutate(klasse = as.factor(klasse))
```

```{r}
abc_analyse_nach_zugriffen %>% 
  head(10)
```



```{r}
abc_analyse_nach_zugriffen <- abc_analyse_nach_zugriffen %>% 
  rename(anteil_zugriffe = anteil, anteil_zugriffe_kumuliert = anteil_kumuliert) %>% 
  mutate(anteil_artikel = row_number()/n())
```

```{r}
x_B <- abc_analyse_nach_zugriffen %>% 
  filter(klasse == "B") %>% 
  arrange(rang) %>%
  head(1) %>% 
  pull("anteil_artikel")

x_C <- abc_analyse_nach_zugriffen %>% 
  filter(klasse == "C") %>% 
  arrange(rang) %>%
  head(1) %>% 
  pull("anteil_artikel")


 abc_analyse_nach_zugriffen %>% 
  ggplot() +
  geom_line(mapping = aes(x=anteil_artikel*100, y=anteil_zugriffe_kumuliert*100, color=klasse)) +
  geom_hline(yintercept = 0, size=0.8) + 
  geom_vline(xintercept = 0, size=0.8) +
  geom_vline(xintercept = c(x_B, x_C)*100, linetype="dashed") +
  scale_x_continuous(breaks = round(c(0, x_B, x_C, 1)*100, digits=1)) +
  scale_y_continuous(breaks = seq(from=0, to=100, by=20)) +
  coord_fixed(ratio = 1) +
  labs(
    x = "Anteil Artikel (in %)", 
    y = "Anteil Zugriffe kumuliert (in %)",
    color = "Klasse",
    title = "ABC-Analyse nach Zugriffen"
  )
```

```{r}
abc_analyse_nach_zugriffen %>% nrow()
```
```{r}
abc_zugriffe %>% nrow()
```


## Nach Umsatz
```{r}
abc_analyse_nach_umsatz <- verkaeufe %>% 
  group_by(materialnummer) %>% 
  summarise(umsatz = sum(vk_preis_num)) %>% 
  arrange(desc(umsatz)) %>% 
  mutate(rang=row_number()) %>% 
  mutate(anteil = umsatz/sum(umsatz)) %>% 
  mutate(anteil_kumuliert = cumsum(anteil)) %>% 
  mutate(klasse=
           case_when(
             anteil_kumuliert <= 0.8 ~ "A",
             anteil_kumuliert > 0.8 & anteil_kumuliert <= 0.9 ~ "B",
             TRUE ~ "C"
             )
         ) %>% 
  mutate(klasse = as.factor(klasse))
```

```{r}
abc_analyse_nach_umsatz %>% 
  head(10)
```


```{r}
abc_analyse_nach_umsatz <- abc_analyse_nach_umsatz %>% 
  rename(anteil_umsatz = anteil, anteil_umsatz_kumuliert = anteil_kumuliert) %>% 
  mutate(anteil_artikel = row_number()/n())
```

```{r}
x_B <- abc_analyse_nach_umsatz %>% 
  filter(klasse == "B") %>% 
  arrange(rang) %>%
  head(1) %>% 
  pull("anteil_artikel")

x_C <- abc_analyse_nach_umsatz %>% 
  filter(klasse == "C") %>% 
  arrange(rang) %>%
  head(1) %>% 
  pull("anteil_artikel")
   
abc_analyse_nach_umsatz %>% 
  ggplot() +
  geom_line(mapping = aes(x=anteil_artikel*100, y=anteil_umsatz_kumuliert*100, color=klasse)) +
  geom_hline(yintercept = 0, size=0.8) + 
  geom_vline(xintercept = 0, size=0.8) +
  geom_vline(xintercept = c(x_B, x_C)*100, linetype="dashed") +
  # geom_area(aes(y=anteil_umsatz_kumuliert)) +
  scale_x_continuous(breaks = round(c(0, x_B, x_C, 1)*100, digits = 1)) +
  scale_y_continuous(breaks = seq(from=0, to=100, by=20)) +
  # scale_fill_brewer(palette="Dark2") +
  coord_fixed(ratio = 1) +
  labs(
    x = "Anteil Artikel (in %)", 
    y = "Anteil Umsatz kumuliert (in %)",
    color = "Klasse",
    title = "ABC-Analyse nach Umsatz"
  )
```



## Nach Summe von Abgang

```{r}
abc_analyse_nach_abgang <- verkaeufe %>% 
  select(materialnummer, abgang) %>% 
  group_by(materialnummer) %>% 
  summarise(count_abgang=sum(abgang)) %>% 
  arrange(desc(count_abgang)) %>% 
  mutate(rang=row_number()) %>% 
  mutate(anteil_abgang=count_abgang/sum(count_abgang)) %>%
  mutate(anteil_abgang_kumuliert=cumsum(anteil_abgang)) %>% 
  mutate(klasse=
           case_when(
             anteil_abgang_kumuliert <= 0.8 ~ "A",
             anteil_abgang_kumuliert > 0.8 & anteil_abgang_kumuliert <= 0.9 ~ "B",
             TRUE ~ "C"
             )
         ) %>% 
  mutate(klasse = as.factor(klasse)) 
```

```{r}
abc_analyse_nach_abgang %>% 
  head(10)
```

```{r}
abc_analyse_nach_abgang <- abc_analyse_nach_abgang %>% 
  mutate(anteil_artikel=row_number()/n())
```

```{r}
x_B <- abc_analyse_nach_abgang %>% 
  filter(klasse == "B") %>% 
  arrange(rang) %>%
  head(1) %>% 
  pull("anteil_artikel")

x_C <- abc_analyse_nach_abgang %>% 
  filter(klasse == "C") %>% 
  arrange(rang) %>%
  head(1) %>% 
  pull("anteil_artikel")



abc_analyse_nach_abgang %>% 
  ggplot() +
  geom_line(mapping = aes(x=anteil_artikel*100, y=anteil_abgang_kumuliert*100, color=klasse)) +
  geom_hline(yintercept = 0, size=0.8) + 
  geom_vline(xintercept = 0, size=0.8) +
  geom_vline(xintercept = c(x_B, x_C)*100, linetype="dashed") +
  scale_x_continuous(breaks = round(c(0, x_B, x_C, 1)*100, digits = 0)) +
  scale_y_continuous(breaks = seq(from=0, to=100, by=20)) +
  coord_fixed(ratio = 0.5) +
  labs(
    x = "Anteil Artikel (in %)", 
    y = "Anteil Abgänge kumuliert (in %)",
    color = "Klasse",
    title = "ABC-Analyse nach Abgängen"
  )
```




# XYZ-Analyse
Todo



# ABC-XYZ-Analyse
Todo





```{r include=FALSE}
DBI::dbDisconnect(con)
```



